// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "Secure": Application Media Types
//
// Command:
// $ goagen
// --design=github.com/hryktrd/jwtTest/design
// --out=$(GOPATH)\src\github.com\hryktrd\jwtTest
// --version=v1.3.1

package client

import (
	"net/http"
)

// A station of mine (default view)
//
// Identifier: application/vnd.goa.jwt.test.success; view=default
type GoaJWTTestSuccess struct {
	// Always true
	OK bool `form:"ok" json:"ok" yaml:"ok" xml:"ok"`
}

// DecodeGoaJWTTestSuccess decodes the GoaJWTTestSuccess instance encoded in resp body.
func (c *Client) DecodeGoaJWTTestSuccess(resp *http.Response) (*GoaJWTTestSuccess, error) {
	var decoded GoaJWTTestSuccess
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}
