// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "Secure": Application User Types
//
// Command:
// $ goagen
// --design=github.com/hryktrd/jwtTest/design
// --out=$(GOPATH)\src\github.com\hryktrd\jwtTest
// --version=v1.3.1

package client
